# Generated by Django 2.2.4 on 2019-08-20 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manual', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SPECAN',
            new_name='FEP',
        ),
    ]
