# Generated by Django 2.2.4 on 2019-08-21 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manual', '0002_auto_20190820_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='ACTION',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_name', models.CharField(max_length=200)),
            ],
        ),
    ]
