# Generated by Django 2.2.4 on 2019-08-21 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manual', '0003_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='SPECAN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.CharField(max_length=200)),
            ],
        ),
    ]
