# Generated by Django 2.2.4 on 2019-08-21 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manual', '0004_specan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SPECAN',
        ),
    ]
