# Generated by Django 2.2.4 on 2019-08-22 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manual', '0006_equipment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EQUIPMENT',
        ),
    ]
