# Generated by Django 2.2.4 on 2019-08-22 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manual', '0007_delete_equipment'),
    ]

    operations = [
        migrations.CreateModel(
            name='EQUIPMENT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_yes', models.CharField(max_length=200)),
                ('equipment_no', models.CharField(max_length=200)),
            ],
        ),
    ]
