# Generated by Django 2.2.4 on 2019-08-22 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manual', '0008_equipment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='equipment_no',
        ),
    ]
